server:
  port: 9901
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
  instance:
    prefer-ip-address: true
    
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: module
        uri: lb://DETAILS
        predicates:
        - Path=/detail/**
          