server:
  port: 9699
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
  instance:
    prefer-ip-address: true
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: address
        uri: lb://ADDRESS
        predicates:
        - Path=/address/add/**
      - id: modules
        uri: lb://EMPLOYEE
        predicates:
        - Path=/employee/emp/**                  
          
    
